# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22bc553c06a87b831cf4691dcf8651cd4edadfa08bb10c4f68b9fc6fdfcc745ee84d2f1fb39bd6411610e1157fc885e969d655433ffd94a7f693522f3cf4ef95

test:
  secret_key_base: f06a6cf8629eda709ab99209a884e4523a459548e926fb853633cffdb194d69d34b777e24915ec96b21245e549cf93d87c422037c759c123955bb9d665823498

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
